### ISSUE TITLE
YASC DLL

### ISSUE THREAD

**Issue by hbeer54** [jakehedlund/yasc#10]
Hi,

I find your project super interesting. Are you still planning to work more on the actions you describe as "planned"?

One little wish - I would be very happy to find a compiled version of the YASC DLL, since I do not need to change the code at the moment and usually have great trouble (version conflicts) with Visual Studio projects I find on the net. So if it is not too much to ask, I would be sooo grateful if you could add the yasc.dll file to the project.

Many thanks, H.Beer

**Comment by jakehedlund** [comment]
Hi, 

Thanks for the note. The initial release (all required DLLs except GStreamer) can be found on the releases tab (https://github.com/jakehedlund/yasc/releases/download/v1.0/Yasc-x86-1.0.0.zip - note the DLL is "YetAnotherStreamingControl.dll"). However this one is pretty out of date, and may or may not actually work for you. 

As for the "planned" items, I have several of them figured out/implemented elsewhere but life has prevented me from updating this project much. Maybe in the near future.

**Comment by hbeer54** [comment]
Thank you so much!

Best, Heidrun
