### ISSUE TITLE
image overlay

### ISSUE THREAD

**Issue by szybki8562** [jakehedlund/yasc#4]
How I can add image overlay in GStreamer application to pipeline ? Thanks in advance.

var image = ElementFactory.Make("gdkpixbufoverlay");
image["location"] = @"D:\camera.png";
image["overlay-height"] = 200;
image["overlay-width"] = 200;
image["offset-x"] = 100;
image["offset-y"] = 100;
pipeline.Add(image);

What is missing?

StackOverflow can't help. Maybe you can.

**Comment by jakehedlund** [comment]
Did you get this working? I think you need a call to SyncStateWithParent(). I'm assuming you're linking things properly. 

This works for me: 
```
            var img = ElementFactory.Make("gdkpixbufoverlay");
            img["location"] = @"C:\gstreamer\1.0\x86\bin\test.png";
            img["overlay-height"] = 200;
            pipeline.Add(img);
            var ret = tPrev.Link(img.GetStaticPad("sink"));
            if(ret != PadLinkReturn.Ok)
            {
                sysDbg.WriteLine("Error linking image overlay."); 
            }
            img.SyncStateWithParent();  
            tPrev = img.GetStaticPad("src");
```
