### ISSUE TITLE
how to load many video panels in Form1

### ISSUE THREAD

**Issue by nhtdalat** [jakehedlund/yasc#5]
Hello,

I have an idea to load 4 video panels, so I made 4 yascControls (1 - 4) but only yascControl1 works, can you guide me some ideas for this case.

Thank you.

**Comment by jakehedlund** [comment]
Hi,

What kind of cameras are you connecting to? If it is a usb camera, you
cannot have multiple instances connect to the same camera at the same time.
Network cameras should work for this however. The correct way to do this
for usb is to use a Tee element in GStreamer to show the same camera on
multiple panels, but this is more advanced and isn't supported in Yasc. You
could take a look at the code and implement something to do this fairly
easily. Look at the SyncMessage callback function.
